Models/Weather.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;

namespace WeatherApplication.Models
{
    public class Weather
    {

        private SqlConnection con;

        private void Conn()
        {
            string constr = ConfigurationManager.ConnectionStrings["WeatherDB"].ToString();
            con = new SqlConnection(constr);
        }

        public void AddDetails(WeatherEntity obj)
        {
            Conn();
            con.Open();
            // 사용할 로시저의 이름을 설정
            using (SqlCommand com = new SqlCommand("dbo.InsertWeather", con))
            {
                com.CommandType = CommandType.StoredProcedure;
                com.Parameters.AddWithValue("@Region", obj.Region);
                com.Parameters.AddWithValue("@Main_Temp", obj.Main_Temp);
                com.Parameters.AddWithValue("@Min_Temp", obj.Min_Temp);
                com.Parameters.AddWithValue("@Max_Temp", obj.Max_Temp);
                com.Parameters.AddWithValue("@Feel_Temp", obj.Feel_Temp);
                com.Parameters.AddWithValue("@Wind", obj.Wind);
                com.Parameters.AddWithValue("@Date_T", obj.Date_T);
                com.ExecuteNonQuery();
            }
            con.Close();
            con.Dispose();
        }

        public List<WeatherEntity> GetList()
        {
            List<WeatherEntity> weathers = new List<WeatherEntity>();
            Conn();
            con.Open();
            using (SqlCommand com = new SqlCommand("dbo.SelectWeather", con))
            {
                com.CommandType = CommandType.StoredProcedure;
                SqlDataReader rdr = com.ExecuteReader();
                while (rdr.Read())
                {
                    WeatherEntity wea = new WeatherEntity();
                    wea.Region = Convert.ToString(rdr["Region"]);
                    wea.Main_Temp = Convert.ToDouble(rdr["Temp_Main"]);
                    wea.Min_Temp = Convert.ToDouble(rdr["Temp_Min"]);
                    wea.Max_Temp = Convert.ToDouble(rdr["Temp_Max"]);
                    wea.Feel_Temp = Convert.ToDouble(rdr["Temp_Feel"]);
                    wea.Wind = Convert.ToInt64(rdr["Wind"]);
                    wea.Date_T = Convert.ToString(rdr["Date_T"]);
                    weathers.Add(wea);

                }
                rdr.Close();
            }
            con.Close();
            con.Dispose();
            return weathers;
        }
    }
}

Controllers/WeathersController.cs
using System.Web.Mvc;
using WeatherApplication.Models;

namespace WeatherApplication.Controllers
{
    public class WeathersController : Controller

    {
        // GET: Weathers
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public void AddWeathers(WeatherEntity obj)
        {
            Weather wea = new Weather();
            wea.AddDetails(obj);
        }

        public ActionResult ListWeather()
        {
            Weather wea = new Weather();
            var weatherList = wea.GetList();
            return View(weatherList);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 내 ASP.NET 애플리케이션</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #99CCFF; border-bottom: 1px solid aliceblue; ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("날씨 조회", "Index", "Weathers", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("조회 내역", "ListWeather", "Weathers")</li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Weathers/Index.cshtml
@model IEnumerable<WeatherApplication.Models.Weather>

@{
    ViewBag.Title = "Index";
}
<!DOCTYPE html>
<html>
<head>
    <link href="/Content/index-style.css" rel="stylesheet" />
    <link href="Content/bootstrap.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/203cccc5eb.js" crossorigin="anonymous"></script>
</head>
<body style=" background-color: #99CCFF;">
    <div class="container" style="text-align: center;">
        <input style="text-align: center; margin-top: 15px; border: 1px solid #ccc; border-radius:5px;"  type="text" id="message" />
        <input class="btn btn-light send-btn" type="button" id="sendmessage" value="Send" />
        <input type="hidden" id="displayname" />
    </div>
    <div id="discussion">
        <h6 id="info">실시간 채팅</h6>
    </div>

    <div id="card" style="margin: 50px auto auto auto;">
        <h3 id="info">날씨 조회를 원하시는 도시명을 입력해주세요.</h3>
        <input class="form-control cityName" id="cityName-input" style="margin:50px auto 30px auto"  />
        <button class="form-control" id="weather_save">조회 기록 저장</button>

        <div id="card-body">
            <div id="weather-img">
                <img id="weather-image" src="~/Content/Images/rain.svg" />
                <div id="weather"></div>
            </div>
            <div id="weather-info" style="margin-left:50px;">
                <div id="temp"></div>
                <div id="temp-min"></div>
                <div id="temp-max"></div>
                <div id="temp-feel"></div>
                <div id="wind"></div>
            </div>
        </div>
    </div>


    <script src="Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/index.js"></script>
    @section scripts {
        <script src="~/Scripts/jquery.signalR-2.4.3.min.js"></script>
        <script src="~/signalr/hubs"></script>
        <script>
            $(function () {
                var chat = $.connection.chatHub;
                chat.client.addNewMessageToPage = function (name, message) {
                    $('#discussion').append('<div><strong>' + htmlEncode(name)
                        + '</strong>: ' + htmlEncode(message) + '</div>');
                };
                $('#displayname').val(prompt('사용자 이름을 입력해주세요:', ''));
                $('#message').focus();
                $.connection.hub.start().done(function () {
                    $('#sendmessage').click(function () {
                        chat.server.send($('#displayname').val(), $('#message').val());
                        $('#message').val('').focus();
                    });
                });
            });
            function htmlEncode(value) {
                var encodedValue = $('<div />').text(value).html();
                return encodedValue;
            }
        </script>
    }
</body>
</html>

Views/Weathers/ListWeather.cshtml
@{
    ViewBag.Title = "ListWeather";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Member</title>
    <link href="~/Content/List-style.css" rel="stylesheet" />
    <link href="Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div id="card">
        <table class="table" id="card-body">
            <thead>
                <tr class="text-center">
                    <th class="text-center">지역</th>
                    <th class="text-center">현재 온도</th>
                    <th class="text-center">최고 온도</th>
                    <th class="text-center">최저 온도</th>
                    <th class="text-center">체감 온도</th>
                    <th class="text-center">풍량</th>
                    <th class="text-center">조회 날짜</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="text-center">@item.Region</td>
                        <td class="text-center">@item.Main_Temp</td>
                        <td class="text-center">@item.Max_Temp</td>
                        <td class="text-center">@item.Min_Temp</td>
                        <td class="text-center">@item.Feel_Temp</td>
                        <td class="text-center">@item.Wind</td>
                        <td class="text-center">@item.Date_T</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</body>
</html>